### ISSUE TITLE
Autoset not working correctly

### ISSUE THREAD

**Issue by yazzy18** [analogdevicesinc/scopy#1076]
**Environment:**
 - OS Big Sur: [e.g. iOS]
 - FW Version 
 - SW Version or git tag

**Describe the bug**

**To Reproduce**
1. Go to 'Power Supply'
2. Set Positive Power to 5V & Negative Power to -5V
3. Set Signal Generator CH-1 to Triangle, Vp-p=5V, Frequency = 50 Hz, Offset = 2.5V
4. Turn on Oscilliscope
5. Autoset CH-1 
6. notice that exported data is very skewed and not consistent 
6. See error

**Expected behavior**
Have a consistent set of data values (i.e. the data is supposed to produce a x^3 graph)
**Screenshots**
![image](https://user-images.githubusercontent.com/44105474/113523690-ecfee100-956e-11eb-80c8-12f6a391b20f.png)
<img width="973" alt="Screen Shot 2021-04-04 at 4 32 11 PM" src="https://user-images.githubusercontent.com/44105474/113523694-fa1bd000-956e-11eb-8194-d742f8003e80.png">

**Additional context**

The ini files might be useful to reproduce the error.
The ini file is located at: C:/Users/ali/AppData/Roaming/ADI/Scopy.ini
Please consider attaching it.

**Comment by adisuciu** [comment]
Does this only happen when you autoset ? Or when changing timebase / voltsdiv as well ?

**Comment by yazzy18** [comment]
This happens when I auto set. I’ve also been noticing the oscilloscope has
been taking longer than usual to display the graph and measurements since
that crash. It also crashed twice on me yesterday.

**Comment by adisuciu** [comment]
We're aware of some bugs in the autoset feature. We're working on fixing them, however, the fix requires some architecture changes which will not be done in time for v1.3.0. This bug appears on macOS and sporadically on Windows.

https://github.com/analogdevicesinc/scopy/issues/913

Can you screenshot the skewed nonconsistent data ? Could it be because the autoset fails and it sets some random v/div or timebase ? 

-Adrian
