### ISSUE TITLE
adalm2k: wiki page error

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/scopy#1159]
https://wiki.analog.com/university/tools/m2k/scopy/build-windows

"../install_msys_deps.sh"

The script is not there.

Please check your build guides whenever you make changes to the sources.

**Comment by adisuciu** [comment]
Windows is not really used as a reliable development platform. We mainly use linux for that. The script is not reliable because it depends on the current versions pushed by the MSYS2 repo maintainers. The script is mainly used in a CI environment where there is no issue with using the C:. I'm currently working on a script to make it more reliable and use a staging folder. However it will always be reliant on the versions that are pushed by the MSYS2 developers which sometimes are not compatible with our build so some fixes need to be done (quite often). This is why I'm also creating a docker image to prevent this. When all of this will be finished, I'll push the changes, update our CI and update the docs.

https://github.com/analogdevicesinc/scopy-mingw-build-deps/tree/refactor
