### ISSUE TITLE
adalm2000: Scopy firmware version confusion

### ISSUE THREAD

**Issue by jpnielsen** [analogdevicesinc/scopy#1163]
Scopy tells me, that i can upgrade to a newer firmware "0.27" - but i have 0.28 installed
![image](https://user-images.githubusercontent.com/27916597/138100125-5fae91da-9e8f-4d60-b7b0-20ad37723d85.png)

iio_attr doesn't work as [advertised](https://wiki.analog.com/university/tools/pluto/users/firmware)

```
iio_attr -a -C fw_version

Fatal: program compiled against libxml 2 using libxml 20
Fatal: program compiled against libxml 2 using libxml 20
Multiple contexts found. Please select one using --uri:
        0: 0456:b672 (Analog Devices Inc. M2k (ADALM-2000)), serial=104473ce69910018f5ff070045f4884c0e [usb:4.6.5]
        1: 192.168.2.1 (Analog Devices M2k Rev.D (Z7010)), serial=104473ce69910018f5ff070045f4884c0e [ip:m2k.local]
```

**Comment by AlexandraTrifan** [comment]
Hi,

The info message that Scopy displays is indeed an issue. It requires an update of the version in our backend, which is what we are working on. But this should not influence the way Scopy works.

Regarding iio_attr, you can specify the URI for the context you want to connect to.
For example: 
`iio_attr --uri "ip:192.168.2.1" -C fw_version `

Using "-a" scans and connects to a detected context, if there is only one. But since there were 2 detected available contexts, you need to specify which one should be used.

-Alexandra

**Comment by adisuciu** [comment]
This should be fixxed
