### ISSUE TITLE
Network Analyzer: Phase response after cutoff frequency rises

### ISSUE THREAD

**Issue by jpineda3** [analogdevicesinc/scopy#1331]
**Environment:**
 - OS: Windows 10
 - FW Version: v0.28
 - SW Version or git tag: v1.4.0 rc2 https://github.com/analogdevicesinc/scopy/commit/cca49b2ba901f8d8c40327c689761c87db368fa9

**Describe the bug**
The phase response well beyond the cutoff frequency (fc) rises when it is expected to remain at a steady value. The issue is more noticeable on low-pass filter circuits with frequency sweep settings at high frequencies. The issue manifests as spikes in the phase plot that would continue to rise. High-pass filter circuits also exhibit phase fluctuations at very lower frequencies below the cutoff.

**To Reproduce**
I setup 2 circuits at with different cutoff frequencies. (fc = 340Hz with R = 470 Ohms C = 1uF and fc = 15.9kHz with R = 100 Ohms C = 0.1uF). The instructions below are for fc = 340Hz.
1. Go to Network Analyzer.
2. Setup the instrument to sweep from 10Hz to 500kHz.
3. Limit the Magnitude from -40dB to 5dB, Phase from -100deg to 5 deg.
4. Run the instrument and observe how the phase plot rises after fc. The minimum phase also did not reach -90deg.

**Expected behavior**
The phase plot should approach -90deg and remain at -90deg.

**Screenshots**
fc = 340Hz
![lpf_phase](https://user-images.githubusercontent.com/76926625/165710653-a4c73f77-1467-40cb-bd37-1a1eafe9c6b5.png)

fc = 15.9kHz For this case, the magnitude plot also exhibited fluctuations.
![15p9_lpf_phase](https://user-images.githubusercontent.com/76926625/165711063-337b209a-c51c-4998-974f-5d20ea18e6f1.png)

**Additional context**
Attached are the ini files for fc = 340Hz.
[340_lpf_phase.zip](https://github.com/analogdevicesinc/scopy/files/8580947/340_lpf_phase.zip)

**Comment by adisuciu** [comment]
In the first graph, the phase response is looking as expected because the frequency response goes down to 40dB which is manageable by the ADC. The frequency response is very low(-60 , -70 db) when you are getting the phase response spike. Basically you are measuring just noise at this point and the buffer previewer could probably confirm this. If the circuit allows it, you could increase the reference amplitude, but it wouldn't make that much of a difference.

This is not a bug, the network analyzer works as expected
