### ISSUE TITLE
Logic analyzer: Setting a trigger will shift the view to show the lower pins if they're not shown on the screen

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#138]
OS: Windows 7 64bit
Scopy Version: 1839ee5
Firmware Version: v0.13

Open Logic Analyzer instrument

1. Set any DIO’s trigger while DIO15 is not shown on the screen

![logic analyzer 3](https://user-images.githubusercontent.com/20266602/27718747-74e388bc-5d80-11e7-98de-64cdbf99c496.png)

2. The view will shift to show the lower end pins. It's not very convenient to keep on scrolling up when you still want to set the trigger of all the upper pins.

"This kind of  feature should be present when “group with selected” button is clicked since the group is initially created below."

**Comment by AlexandraTrifan** [comment]
Fixed with commit 9fd35a5e2f35f81252b1539eef712813b1c8e249.
Whenever a trigger is set, the position of the scroll area stays the same. 
In addition, when a group is created with the 'Group with selected' button, the scroll area changes its position to display the newly added group, at the bottom of the list.

**Comment by amiclaus** [comment]
On Scopy build: 1e648f6 the bug is fixed.
