### ISSUE TITLE
Voltmeter: When a channel is in DC mode, switching the other channel's mode will reset the measurement

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#144]
OS: Windows 7 64bit
 Scopy Version:  3021dec
 Firmware Version: v0.13

Open Voltmeter instrument:

1. Set Channel 1 to DC mode
2. Connect scope ch1+ to positive power supply and scope ch1- to gnd.
3. Set the positive power supply to any voltage level, e.g. 3.3V
4. Switch channel 2's mode from DC to AC or AC to DC.

Result: Channel 1's voltage reading will reset to 0 and settle again to the voltage input. Channel 2 has a similar behavior in DC Mode.

This behavior doesn't happen in AC Mode.

![voltmeter bug 1](https://user-images.githubusercontent.com/20266602/27821574-54cb30f4-60d5-11e7-8149-b462c126f20d.png)
![voltmeter bug 1a](https://user-images.githubusercontent.com/20266602/27821585-5aa02be2-60d5-11e7-9b13-9b0b3745f80b.png)

**Comment by pcercuei** [comment]
Long story short: we have a hack in place (https://github.com/analogdevicesinc/scopy/blob/master/src/iio_manager.hpp#L90) that used to be a workaround for a bug in GNU Radio. The bug was fixed, but it appears that the hack is still needed, otherwise we get lockups in the data stream. This is a side effect of that hack.

**Comment by amiclaus** [comment]
Update: the bug is still valid on Scopy v0.10.

**Comment by adisuciu** [comment]
This was fixed at some point.
