### ISSUE TITLE
When first starting Scopy, the license info box is a Yes/No window

### ISSUE THREAD

**Issue by DeflateAwning** [analogdevicesinc/scopy#1521]
Installed via Flatpak

The info box should say what yes/no means. Presumably, it's asking if I agree to the term; it didn't explicitly say that though. I just presented the agreement.

**Comment by AlexandraTrifan** [comment]
Hi,

In the process of redesigning Scopy we also changed the way the license pop-up is presented to the user. If you'll try the Scopy v2.0.0 release candidate, you'll see that the license pop-up now provides 2 options: Exit and Continue. If you choose to continue, it means you agree to the license, otherwise you will not be able to use the application.

Attaching a screenshot from Scopy.
![image](https://github.com/user-attachments/assets/cf82fb1e-34ef-461e-9556-9d05e6b6d37a)

Thank you!
