### ISSUE TITLE
Channel settings position value

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#157]
When trigger position is in right side on the screen the position value should always be a negative value, but if you move the trigger with the mouse cursor that value is sometimes positive.
![trig_pos_bug](https://user-images.githubusercontent.com/13637543/27948852-00e2ec26-6304-11e7-966f-323792647b4e.png)
![trig_pos_bug_2](https://user-images.githubusercontent.com/13637543/27948919-3eb197e6-6304-11e7-8b8a-c103bbbdc75d.png)

**Comment by dNechita** [comment]
In reality, the value doesn't jump from positive to negative (it only appears to do that). Because there are too many decimals and not that much space, the entire number gets shifted to the left and hides the minus sign.
This commit fixes the issue: https://github.com/analogdevicesinc/scopy/commit/1b52ce4ea52bc5e9b5b8b73a3e4ea9c318d1a1a1

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.
