### ISSUE TITLE
Oscilloscope stop acquisition

### ISSUE THREAD

**Issue by msuciu** [analogdevicesinc/scopy#193]
Oscilloscope stop acquisition when signal generator is running and the time base is higher than 5 ms. 
To detect this connect Signal Generator channel 1 or 2 output on Oscilloscope channel 1 or 2 input.
![image](https://user-images.githubusercontent.com/13637543/28467848-e2b0e974-6e39-11e7-9bc4-d67b7b663e50.png)
![image](https://user-images.githubusercontent.com/13637543/28467904-0c878258-6e3a-11e7-86ec-3513cae455ff.png)
![image](https://user-images.githubusercontent.com/13637543/28467916-1331e6b6-6e3a-11e7-88b1-b4c35e6bb8be.png)

**Comment by dNechita** [comment]
The acquisition doesn't stop. It just captures samples close to 0 Volts.
You are capturing a 10 kHz signal with a sample rate of 10 kSPS. You are way off the Nyquist limit.
However, I'm not sure why the signal is leveled. It might be due to the HDL filters or something else.
Either way, you won't be able to get a proper representation of that signal with the current sample rate.
