### ISSUE TITLE
Signal unstable at low frequencies

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#208]
Scopy version: 8406b30

I'm using a RC HPF (10k, 39pF) with the Network Analyzer- see https://github.com/analogdevicesinc/scopy/issues/168#issuecomment-314133868 for more info regarding HPF

I'm going on a 100Hz-10MHz sweep. At low frequencies the plot result is quite unstable.
Below is a comparison between M2K and Discovery using same setup.
![cr_hpf-wav](https://user-images.githubusercontent.com/26061529/28712606-76afc564-7394-11e7-8595-1c4d4fb4988d.PNG)
![cr_hpf-wav-2](https://user-images.githubusercontent.com/26061529/28712607-76b0bf6e-7394-11e7-99f2-fb8af6b8c7d7.PNG)

**Comment by damercer** [comment]
This could be due to the larger LSB in M2K ( 12bits vs 14 bits or 12 dB). Or, which gain range is the input stage set to? If it is in the +/- 25 V range the LSB is huge.

Doug

**Comment by adisuciu** [comment]
This issue seems to be solved in the latest Scopy version. There are no visible spikes when the amplitude is low.
![scopy_2018-01-23_11-22-31](https://user-images.githubusercontent.com/8676912/35269224-19b5c6b0-0034-11e8-8e3d-97a909b72576.png)
![scopy_2018-01-23_11-53-19](https://user-images.githubusercontent.com/8676912/35269225-19fd68c6-0034-11e8-97bc-4f7438cdbe96.png)

**Comment by amiclaus** [comment]
On Scopy build: 2e31a75 (v0.11) the bug is fixed.
