### ISSUE TITLE
Select and group again a group has different effect in logic analyzer and pattern generator

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#267]
Scopy build:  [316a80e](https://github.com/analogdevicesinc/scopy/commit/316a80e86b210362c6591435e8c64d4e335fd03a)

Steps:
Select DIO0 and click 'Group with selected'.
Once the group is created, select that group and click again 'Group with selected'.

In pattern generator, when selecting and grouping again a group, the group is dissolved.

Whereas in logic analyzer, when doing so, the group is duplicated.

Is there  a significance in the difference?
I'm not sure if this is a bug. So I'm adding this as a question.

**Comment by adisuciu** [comment]
This is the expected behavior.

Logic analyzer deals with inputs, while pattern generator deals with outputs. Outputs can only be driven by one source, therefore the channels cannot be duplicated - you can't have both a clock signal and a UART line on the same output.

However, when dealing with inputs, you can have the same signal processed by multiple decoders. When selecting a group and click "group" the logic analyzer creates a copy of the selected group. This new selected group can have different parameters. The signals are the same but the interpretation of the signals is different.

The same goes for single signals that can be standalone or can be included in multiple groups.
