### ISSUE TITLE
Spectrum Analyzer: Resolution BW not updated when Stop or Start frequency is not changed manually

### ISSUE THREAD

**Issue by drbautista** [analogdevicesinc/scopy#274]
OS: Windows 7 64bit
 Scopy Version:  b4a4b353
 Firmware Version: v0.14

Set the Signal generator to 10V amplitude and frequency at 1kHz.

Set the  Span first at 2kHz then the Center frequency at 1 kHz.
The start and Stop frequency will automatically adjust to 0 Hz and 2kHz respectively.
However, The resolution BW won't be updated unless there's a manual change on the start or stop frequency.

![resolution bug](https://user-images.githubusercontent.com/20266602/30846118-df569c2e-a2c8-11e7-8c6f-9c8e9ab1ee4c.png)

**Comment by dNechita** [comment]
Cannot reproduce. The RBW dropdown list changes regardless of the instrument running state.

Changing the start and stop frequencies doesn't always need to update the RBW dropdown. The update is required only when the sample rate changes. At a given sample the instrument can detect frequencies at half of that, therefore it always run at the lowest sample rate it can.
Lets say the highest sample rate is 100MSPS. For stop frequencies greater than 25MHz and up to 50MHz it runs at 100MSPS. For stop frequencies in the range of 16.66 ->25MHz the sample rate is lowered at 50MSPS since the highest sample rate can be divided only by integer values (1, 2, 3, ...). And so on.
