### ISSUE TITLE
Burger menu enabled whenever other menu is enabled.

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#282]
Scopy version: 07380f6

I.e. select gear menu to open open the general settings pannel. The burger menu icon is simultaneously enabled. This happens also when opening other pannels like channel settings, measure, etc.
![image](https://user-images.githubusercontent.com/26061529/31279828-26e6eaca-aab3-11e7-9d57-db878ffc3d26.png)

**Comment by AlexandraTrifan** [comment]
The _settings_ button (burger menu icon) should be checked every time one of the following buttons is checked: measure button, cursors button, trigger button, channels buttons. This button handles the last settings panel that was opened.
The _general settings_ button (gear wheel) should disable all the other checked buttons. This button handles the general settings panel and should not interact with the _settings_ button.
This is fixed with commit 1a22c4adf897f968fb015cf9f4b3b6fd2e33dd53.

**Comment by amiclaus** [comment]
On Scopy build: 704cb7f (v0.8) the bug is fixed.
