### ISSUE TITLE
To gray out data logging feature when turned off

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#492]
Scopy version: [1d173e63](https://github.com/analogdevicesinc/scopy/commit/1d173e633165f0632036963f0b15180598c5add9)
OS: Windows 10
Firmware version: 0.21

When data logging is turned off, the user can still configure the settings relating to data logging. this might cause confusion on the user. Perhaps graying out the feature just like the External Trigger settings in Oscilloscope.
![image](https://user-images.githubusercontent.com/25096080/46594100-9500d400-cb03-11e8-89c2-47841fe54564.png)

**Comment by AlexandraTrifan** [comment]
Commit d6b1429b7cd726317cac5fbf6e62d27d370e7f2b implements the following behaviour: The controls for data logging are greyed out when the Voltmeter is not running and the data logging is OFF. If we start the Voltmeter, the controls are not greyed out, because the user needs to be able to preset the data logging feature.

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the feature is implemented.
