### ISSUE TITLE
Print button is not uniform among instrument

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/scopy#499]
Scopy build: [e3efb590](https://github.com/analogdevicesinc/scopy/commit/e3efb5903bd9b89aff8d275be25b43111a3c65b4)

As seen in the picture below, the print button is not uniform among instrument
![image](https://user-images.githubusercontent.com/25096080/46670582-1d1ad280-cc05-11e8-8f5e-12826c7d6e15.png)

**Comment by AlexandraTrifan** [comment]
Should be fixed with commit 27eebb880e1ca5b0f465163e9827a4fad6863917 . 
For the Logic Analyzer, since there is not enough space, the button has 2 states: The one you posted, and the following one, which is the same as in the Oscilloscope: 
![logic-print](https://user-images.githubusercontent.com/18142097/46678356-2304b980-cbed-11e8-8be5-f21af8f9a092.PNG)

**Comment by amiclaus** [comment]
On Scopy build (v1.0.2): d6b1429 the bug is fixed.
