### ISSUE TITLE
No output signal when pushing at max frequency

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#514]
Scopy version: 91c4f0c
Firmware: v0.22

Push the SG to max frequency: 37.5MHz

Result:
No signal is generated.

Decrease frequency: 37.4MHz and below

The SG starts to generate output signal. 

Verified with both Scopy Osc and real Osc.

**Comment by adisuciu** [comment]
This is due to the way the sinewave is generated by gnuradio, having a sinewave at samplingfrequency/2 with 0 phase, basically gives out a stream of 0 amplitude samples. It's not ideal but it's the way it works when hitting the limits of the device. To circumvent this, try setting phase to 90 degrees.

**Comment by amiclaus** [comment]
Indeed, having at disposal only 2 samples, for any phase which is multiple of 180deg the output will be the offset of the signal. Shouldn't we limit the software frequency range at a value that actually outputs the expected signal?

**Comment by adisuciu** [comment]
Well, I don't know. It works correctly just for 90 degrees.If we decide to limit the frequency, how much distortion should be allowed ?

**Comment by mbanciso** [comment]
The AWG frequency should be limited to 30 MHz.

**Comment by adisuciu** [comment]
Implemented with 9dda1740cfee2797670f35bc02801b175611dbe1

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the bug is fixed.
