### ISSUE TITLE
Plot curve visualization options

### ISSUE THREAD

**Issue by adisuciu** [analogdevicesinc/scopy#529]
QwtPlot supports multiple types of data rendering. Currently we only render data using lines (or interpolation method). Implement other visualization methods (like point or sample/hold)

**Comment by damercer** [comment]
I think in Scopy with the high sample rate of M2K and the limit set on the smallest time/div setting allowed, the sample points are closely spaced so that drawing straight lines between points is often good enough to render nice traces. However another rendering option you might look at is some sort of smooth curves like splines to connect the dots. Again, this only helps visually if the sample points are many pixels apart ( like having only a few samples per horizontal time division ).
Anyway, just a thought.
Doug

**Comment by adisuciu** [comment]
Fixed with https://github.com/analogdevicesinc/scopy/pull/556

**Comment by amiclaus** [comment]
On Scopy version: e28686c (v1.0.5) the feature is implemented
