### ISSUE TITLE
User Rights in Linux? Scopy without sudo

### ISSUE THREAD

**Issue by msambg** [analogdevicesinc/scopy#533]
I installed with flatpack installer under Mint 19.
when I start with sudo, everything works fine. I added user to group dialout. 
When I start without sudo, it starts, shows the ADALM2000, tries to connect, but while connecting Scopy crashes. Must be a problem of user rights. 
Any idea to fix that? I want to use without sudo.

**Comment by adisuciu** [comment]
Hey,

Did you run these steps to install the ADALM2000 drivers ?  - https://wiki.analog.com/university/tools/pluto/drivers/linux

Specifically  - 
"In order to access some USB functions without root privileges, it's recommended to install the PlutoSDR or ADALM2000 udev rules. Simply download 53-adi-plutosdr-usb.rules and copy into into the /etc/udev/rules.d/ folder. You can also use this plutosdr-m2k-udev.deb package to install both the PlutoSDR and the ADALM2000 udev rules. To install the debian package, use one of the following: sudo apt-get install ./plutosdr-m2k-udev.deb or sudo dpkg -i plutosdr-m2k-udev.deb. 
Afterwards reload rules or restart udev, using either udevadm control --reload-rules or sudo service udev restart"

-Adrian
