### ISSUE TITLE
History Reverse Axis Option

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#62]
"Connect M2K. Start Scopy, select the detected device. Press "Connect" button. After the connection is made, select Voltmeter feature.
Actual Results: History Time Axis -> Vertical; History Voltage Axis -> Horizontal. 
Expected Results: Reverse Axis Option should be introduced so that the user can switch axis: History Time Axis -> Horizontal; History Voltage Axis -> Vertical. "

**Comment by rgetz** [comment]
Can you describe a student centric lab, where this feature is necessary? 

I'm not sure I understand the purpose. The stripchart in the voltmeter tool is a stripchart. 
https://en.m.wikipedia.org/wiki/Chart_recorder

All voltmeter/stripchart tools that I am familiar with use a galvanometer, and things flow down. 

If you need time to flow horizontally, that's a oscilloscope.

**Comment by amiclaus** [comment]
This feature is not necessary, but I find it useful since when I first used the Voltmeter feature I was a bit confused about that representation and its meaning, being accustomed with the evolution of a signal in time being described using the horizontal axis for the time variable.

**Comment by rgetz** [comment]
That's because you are already familiar with a scope. :)

**Comment by damercer** [comment]
There are some physical strip-chart like devices that have time on the horizontal axis. Like a lie detector for example. Like most things one can always find exceptions to the "rule". Just because of a preconception of what is proper should not automatically rule out other options. Most computer screens ( tablets as well ) are used in landscape orientation so the long axis ( which in most cases is time ) will be horizontal.

**Comment by amiclaus** [comment]
Since there is no clearly stated favorable feedback regarding this enhancement, the post will be closed.
